"""Initial

Revision ID: 22c75be5848e
Revises:
Create Date: 2026-03-22 19:45:08.459187

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '22c75be5848e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'organizations',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('slug', sa.String(length=50), nullable=False),
        sa.Column('created_by_id', sa.BIGINT(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('NOW()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('slug'),
    )
    op.create_table(
        'users',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('fullname', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=150), nullable=False),
        sa.Column(
            'phone',
            sa.String(length=20),
            server_default=sa.text("''"),
            nullable=False,
        ),
        sa.Column('password', sa.String(length=128), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('NOW()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    op.create_table(
        'addresses',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('organization_id', sa.BIGINT(), nullable=False),
        sa.Column('address', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ['organization_id'],
            ['organizations.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'subjects',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('organization_id', sa.BIGINT(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('image', sa.Text(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False, server_default=sa.text("''")),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('NOW()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['organization_id'],
            ['organizations.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('organization_id', 'name', name='uq_subjects_org_name'),
    )
    op.create_table(
        'courses',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('subject_id', sa.BIGINT(), nullable=False),
        sa.Column(
            'type',
            sa.Enum('GROUP', 'INDIVIDUAL', name='course_type'),
            nullable=False,
        ),
        sa.Column('price', sa.Integer(), nullable=False),
        sa.Column(
            'payment_type',
            sa.Enum('FULL_COURSE', 'EVERY_LESSON', name='course_payment_type'),
            nullable=False,
        ),
        sa.Column(
            'lesson_type',
            sa.Enum('ONLINE', 'OFFLINE', 'MIXED', name='lesson_type'),
            nullable=False,
        ),
        sa.Column('lesson_duration', sa.Interval(), nullable=False),
        sa.Column('lessons_count', sa.Integer(), nullable=True),
        sa.Column('duration', sa.Interval(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('NOW()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['subject_id'],['subjects.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'organization_members',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('organization_id', sa.BIGINT(), nullable=False),
        sa.Column('user_id', sa.BIGINT(), nullable=False),
        sa.Column(
            'role',
            sa.Enum('STUDENT', 'TEACHER', 'ADMIN', 'OWNER', name='user_role'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('NOW()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['organization_id'],
            ['organizations.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_user'),
    )
    op.create_table(
        'cabinets',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('address_id', sa.BIGINT(), nullable=False),
        sa.Column('number', sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(
            ['address_id'],
            ['addresses.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'address_id', 'number', name='uq_cabinets_address_number',
        ),
    )
    op.create_table(
        'course_teachers',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('course_id', sa.BIGINT(), nullable=False),
        sa.Column('teacher_id', sa.BIGINT(), nullable=False),
        sa.Column(
            'is_active',
            sa.Boolean(),
            server_default=sa.text('true'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('NOW()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['course_id'],
            ['courses.id'],
        ),
        sa.ForeignKeyConstraint(
            ['teacher_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'feedback',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('author_id', sa.BIGINT(), nullable=False),
        sa.Column('teacher_id', sa.BIGINT(), nullable=True),
        sa.Column('course_id', sa.BIGINT(), nullable=True),
        sa.Column('rating', sa.Integer(), nullable=False),
        sa.Column(
            'text', sa.Text(), server_default=sa.text("''"), nullable=False,
        ),
        sa.Column(
            'is_active',
            sa.Boolean(),
            server_default=sa.text('true'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('NOW()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['author_id'],
            ['users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['course_id'],
            ['courses.id'],
        ),
        sa.ForeignKeyConstraint(
            ['teacher_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'groups',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('course_id', sa.BIGINT(), nullable=False),
        sa.Column('default_cabinet_id', sa.BIGINT(), nullable=True),
        sa.Column('max_users_count', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('NOW()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['course_id'],
            ['courses.id'],
        ),
        sa.ForeignKeyConstraint(
            ['default_cabinet_id'],
            ['cabinets.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'course_teacher_students',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('course_teacher_id', sa.BIGINT(), nullable=False),
        sa.Column('student_id', sa.BIGINT(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('NOW()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['course_teacher_id'],
            ['course_teachers.id'],
        ),
        sa.ForeignKeyConstraint(
            ['student_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'lessons',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('group_id', sa.BIGINT(), nullable=True),
        sa.Column('course_teacher_student_id', sa.BIGINT(), nullable=True),
        sa.Column('cabinet_id', sa.BIGINT(), nullable=True),
        sa.Column('url', sa.String(length=500), nullable=True),
        sa.Column('conducted_by_id', sa.BIGINT(), nullable=False),
        sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('NOW()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['cabinet_id'],
            ['cabinets.id'],
        ),
        sa.ForeignKeyConstraint(
            ['conducted_by_id'],
            ['users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['group_id'],
            ['groups.id'],
        ),
        sa.ForeignKeyConstraint(
            ['course_teacher_student_id'],
            ['course_teacher_students.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'user_groups',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('user_id', sa.BIGINT(), nullable=False),
        sa.Column('group_id', sa.BIGINT(), nullable=False),
        sa.Column(
            'is_active',
            sa.Boolean(),
            server_default=sa.text('true'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('NOW()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['group_id'],
            ['groups.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'attendance',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('lesson_id', sa.BIGINT(), nullable=False),
        sa.Column('user_id', sa.BIGINT(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('PRESENT', 'ABSENT', 'EXCUSED', name='attendance_status'),
            nullable=False,
        ),
        sa.Column(
            'comment', sa.Text(), server_default=sa.text("''"), nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['lesson_id'],
            ['lessons.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'payments',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('group_id', sa.BIGINT(), nullable=True),
        sa.Column('user_id', sa.BIGINT(), nullable=True),
        sa.Column('lesson_id', sa.BIGINT(), nullable=True),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.Column('created_by_id', sa.BIGINT(), nullable=False),
        sa.Column(
            'date',
            sa.DateTime(timezone=True),
            server_default=sa.text('NOW()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['created_by_id'],
            ['users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['group_id'],
            ['groups.id'],
        ),
        sa.ForeignKeyConstraint(
            ['lesson_id'],
            ['lessons.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('attendance')
    op.drop_table('user_groups')
    op.drop_table('lessons')
    op.drop_table('course_teacher_students')
    op.drop_table('groups')
    op.drop_table('feedback')
    op.drop_table('course_teachers')
    op.drop_table('cabinets')
    op.drop_table('organization_members')
    op.drop_table('courses')
    op.drop_table('addresses')
    op.drop_table('users')
    op.drop_table('subjects')
    op.drop_table('organizations')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS user_role")
    op.execute("DROP TYPE IF EXISTS course_type")
    op.execute("DROP TYPE IF EXISTS lesson_type")
    op.execute("DROP TYPE IF EXISTS course_payment_type")
    op.execute("DROP TYPE IF EXISTS attendance_status")
